# Generated by Django 5.1.3 on 2024-11-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livresEmprunté', to='livres.livre'),
        ),
    ]
